trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  ConnectionStrings.MealPlanner: $(MealPlannerConnectionString)
  Google.ClientId: $(GoogleClientId)
  Google.ClientSecret: $(GoogleClientSecret)

steps:
- task: CmdLine@2
  inputs:
    script: 'dotnet tool restore'

- task: CmdLine@2
  inputs:
    script: 'dotnet fake build -t bundle'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'deploy'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true 

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: $(AzureSubscription)
    appType: 'webApp'
    WebAppName: 'meal-planner-cv'
    packageForLinux: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    JSONFiles: '**/appsettings.json'